Update pools.json
garlicoin-project/insight-grlc-api pull request #7
Opened 2018-02-14 18:43 UTC by MrSol0

add grlc.co

2018-02-14 20:16 UTC, meric426 requested changes
This pool is shit. Make it better before merging this PR.

2018-02-14 21:23 UTC, MrSol0 commented
shit? what are you talking about?

2018-02-14 21:43 UTC, ryan-shaw commented on pools.json
> +		"url": "http://grlc.co/",
Get some HTTPS on this then I'll merge.

2018-02-15 07:47 UTC, meric426 commented
Also it's run entirely by ASIC's. It won't be around after the fork, no need to merge this.

2018-02-16 18:57 UTC, closed without merging